Repository fluxcd/helm-controller, pull requests merged in 2020-08, with the labels that each got.

#49 Update Helm package to v3.3.0
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/helm

#51 Make use of dedicated fluxcd/pkg modules
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#54 Allow overwrites of map values with flat values
  controllers/helmrelease_controller.go
Labels: bug

#56 Make various make targets work after api pkg change
  Makefile
Labels: bug

#55 Support targeting a path in ValuesReferences
  .github/workflows/e2e.yaml
  Makefile
  api/v2alpha1/reference_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  config/testdata/valuesfrom/configmap.yaml
  config/testdata/valuesfrom/golden.txt
  config/testdata/valuesfrom/helmrelease.yaml
  config/testdata/valuesfrom/secret.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
  docs/spec/v2alpha1/helmreleases.md
Labels: area/UX, area/helm, enhancement

#58 api: make optional structs pointers
  api/v2alpha1/condition_types.go
  api/v2alpha1/helmrelease_types.go
  api/v2alpha1/reference_types.go
  api/v2alpha1/sort.go
  api/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
  docs/spec/v2alpha1/helmreleases.md
Labels: bug
