Repository fluxcd/helm-controller, pull requests merged in 2020-09, with the labels that each got.

#61 More graceful failure recovery
  api/v2alpha1/helmrelease_types.go
  api/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
  docs/spec/v2alpha1/helmreleases.md
Labels: area/UX, enhancement

#65 Update README
  README.md
Labels: area/docs

#66 doc/spec: several updates and fixes
  docs/spec/README.md
  docs/spec/v2alpha1/README.md
  docs/spec/v2alpha1/helmreleases.md
Labels: area/docs

#68 Publish amd64/arm64 images to GHCR
  .github/workflows/release.yml
  Dockerfile
Labels: area/build

#72 Configure manager logging and set level to info
  config/manager/deployment.yaml
  main.go
Labels: enhancement

#74 Bump runtime and build-push-action versions
  .github/workflows/release.yml
  go.mod
  go.sum
Labels: area/build

#76 Include PATCH rule for events in manager-role
  Makefile
  config/rbac/role.yaml
  controllers/helmrelease_controller.go
Labels: bug

#77 Support HelmChart ValuesFile field
  api/v2alpha1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  config/default/kustomization.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
  go.mod
  go.sum
Labels: area/helm, enhancement

#78 Remove `find -execdir` from `Makefile`
  Makefile
Labels: area/build, bug

#79 Add watch all namespaces flag
  config/manager/deployment.yaml
  main.go
Labels: enhancement

#75 Refactor status API
  .github/workflows/e2e.yaml
  api/v2alpha1/condition_types.go
  api/v2alpha1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
  docs/spec/v2alpha1/helmreleases.md
Labels: area/UX, enhancement

#82 Support dependency references to other namespaces
  api/go.mod
  api/go.sum
  api/v2alpha1/helmrelease_types.go
  api/v2alpha1/sort.go
  api/v2alpha1/sort_test.go
  api/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  config/testdata/dependencies/helmrelease-frontend.yaml
  controllers/helmchart_watcher.go
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
  go.mod
  go.sum
  hack/api-docs/config.json
Labels: area/UX, enhancement

#85 spec: add validation rules for (namespace)names
  api/v2alpha1/helmrelease_types.go
  api/v2alpha1/reference_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/spec/v2alpha1/helmreleases.md
Labels: area/UX, enhancement

#84 ci: add sanity check for container images
  .github/workflows/release.yml
Labels: area/build

#86 Publish ARM v7/v8 multi-arch image to GHCR
  .github/workflows/release.yml
Labels: area/build

#89 Support Helm charts from Bucket sources
  README.md
  api/v2alpha1/helmrelease_types.go
  api/v2alpha1/reference_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/helmrelease.md
  docs/spec/v2alpha1/helmreleases.md
  go.mod
  go.sum
Labels: enhancement

#88 Support optional values references
  api/v2alpha1/reference_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
Labels: area/UX, enhancement

#95 Fix logging for next run delay
  controllers/helmrelease_controller.go
Labels: bug

#93 Documentation improvements
  api/v2alpha1/condition_types.go
  api/v2alpha1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/helmrelease.md
  docs/spec/README.md
  docs/spec/v2alpha1/README.md
  docs/spec/v2alpha1/helmreleases.md
Labels: area/docs

#98 Remove leftover `lastObservedTime` references
  docs/spec/v2alpha1/helmreleases.md
Labels: area/docs
