Repository fluxcd/helm-controller, pull requests merged in 2020-07, with the labels that each got.

#9 Allow suspending of HelmReleases
  api/v2alpha1/condition_types.go
  api/v2alpha1/helmrelease_types.go
  config/crd/bases/helm.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  controllers/helmrelease_predicate.go
  docs/api/helmrelease.md
Labels: enhancement

#10 Create HelmChart based on provided template
  api/v2alpha1/helmrelease_types.go
  api/v2alpha1/reference_types.go
  api/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/helm.fluxcd.io_helmreleases.yaml
  config/samples/helm_v2alpha1_helmrelease.yaml
  config/samples/source_v1alpha1_helmchart.yaml
  config/testdata/dependencies/helmchart.yaml
  config/testdata/dependencies/helmrelease-backend.yaml
  config/testdata/dependencies/helmrelease-frontend.yaml
  config/testdata/podinfo/helmchart.yaml
  config/testdata/podinfo/helmrelease.yaml
  controllers/helmchart_watcher.go
  controllers/helmrelease_controller.go
  controllers/helmrelease_predicate.go
  docs/api/helmrelease.md
Labels: enhancement

#12 Setup production logging
  config/manager/deployment.yaml
  go.mod
  main.go
Labels: enhancement

#14 CRD tweaks
  api/v2alpha1/helmrelease_types.go
  config/crd/bases/helm.fluxcd.io_helmreleases.yaml
Labels: enhancement

#15 Drop `helm.` prefix from reconcileAt annotation
  api/v2alpha1/helmrelease_types.go
Labels: enhancement

#1 HelmRelease v2alpha1 spec
  README.md
  docs/spec/README.md
  docs/spec/v2alpha1/README.md
  docs/spec/v2alpha1/helmreleases.md
Labels: documentation

#20 Lookup releases in all namespaces in chart watcher
  controllers/helmchart_watcher.go
Labels: bug

#21 Broadcast events for Helm actions
  controllers/helmrelease_controller.go
Labels: area/UX, enhancement

#23 Refactor garbage collection to finalizer
  api/v2alpha1/helmrelease_types.go
  config/crd/bases/helm.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  controllers/helmrelease_predicate.go
  docs/api/helmrelease.md
Labels: enhancement

#26 Support KeepHistory flag for Helm uninstall action
  api/v2alpha1/helmrelease_types.go
  config/crd/bases/helm.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
  docs/spec/v2alpha1/helmreleases.md
Labels: area/UX, area/helm, enhancement

#28 Upgrade CRDs to apiextensions.k8s.io/v1
  .github/workflows/e2e.yaml
  Dockerfile
  Makefile
  config/crd/bases/helm.fluxcd.io_helmreleases.yaml
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: enhancement

#27 Uninstall fixes
  controllers/helmrelease_controller.go
Labels: area/UX, enhancement

#25 Factor out common patterns
  api/v2alpha1/helmrelease_types.go
  controllers/helmrelease_controller.go
Labels: enhancement

#31 Fix: use fetched HelmChart object for update
  controllers/helmrelease_controller.go
Labels: bug

#33 Fix: use composed release name in Helm actions
  controllers/helmrelease_controller.go
Labels: bug

#35 Fix Helm chart update
  config/testdata/dependencies/helmrelease-backend.yaml
  config/testdata/dependencies/helmrelease-frontend.yaml
  config/testdata/dependencies/helmrepository.yaml
  controllers/helmrelease_controller.go
Labels: bug

#38 Reevaluate ready status after transient errors
  controllers/helmrelease_controller.go
Labels: area/helm, bug

#40 Rename conditions to describe the current state
  api/v2alpha1/condition_types.go
  api/v2alpha1/helmrelease_types.go
  controllers/helmrelease_controller.go
  docs/spec/v2alpha1/helmreleases.md
Labels: area/UX

#43 Take observed generation of dependencies into account
  api/v2alpha1/condition_types.go
  controllers/helmrelease_controller.go
Labels: enhancement

#45 Remove local actions and use those from fluxcd/pkg
  .github/actions/helm/Dockerfile
  .github/actions/helm/action.yml
  .github/actions/helm/entrypoint.sh
  .github/actions/kubebuilder/Dockerfile
  .github/actions/kubebuilder/action.yml
  .github/actions/kubebuilder/entrypoint.sh
  .github/actions/kubectl/Dockerfile
  .github/actions/kubectl/action.yml
  .github/actions/kubectl/entrypoint.sh
  .github/actions/kustomize/Dockerfile
  .github/actions/kustomize/action.yml
  .github/actions/kustomize/entrypoint.sh
  .github/workflows/e2e.yaml
  .github/workflows/release.yml
Labels: area/build

#44 Support values from ConfigMap and Secret resources
  .github/workflows/e2e.yaml
  api/v2alpha1/helmrelease_types.go
  api/v2alpha1/reference_types.go
  api/v2alpha1/zz_generated.deepcopy.go
  config/crd/bases/helm.fluxcd.io_helmreleases.yaml
  config/testdata/valuesfrom/configmap.yaml
  config/testdata/valuesfrom/helmrelease.yaml
  config/testdata/valuesfrom/helmrepository.yaml
  config/testdata/valuesfrom/result.txt
  config/testdata/valuesfrom/secret.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
  docs/spec/v2alpha1/helmreleases.md
Labels: area/UX, area/helm, enhancement

#46 Change CRD domain to 'helm.toolkit.fluxcd.io'
  CHANGELOG.md
  PROJECT
  api/v2alpha1/doc.go
  api/v2alpha1/groupversion_info.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/rbac/helmrelease_editor_role.yaml
  config/rbac/helmrelease_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/helm_v2alpha1_helmrelease.yaml
  config/samples/source_v1alpha1_helmchart.yaml
  config/testdata/dependencies/helmrelease-backend.yaml
  config/testdata/dependencies/helmrelease-frontend.yaml
  config/testdata/dependencies/helmrepository.yaml
  config/testdata/podinfo/helmrelease.yaml
  config/testdata/podinfo/helmrepository.yaml
  config/testdata/valuesfrom/helmrelease.yaml
  config/testdata/valuesfrom/helmrepository.yaml
  controllers/helmchart_watcher.go
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
  docs/spec/README.md
  docs/spec/v2alpha1/README.md
  docs/spec/v2alpha1/helmreleases.md
  go.mod
  go.sum
Labels: area/UX, enhancement
