Repository fluxcd/helm-controller, pull requests merged in 2020-11, with the labels that each got.

#140 Update engineerd/setup-kind to v0.5.0
  .github/workflows/e2e.yaml
Labels: area/build

#144 Patch status sub-resource and requeue on some errors
  controllers/helmrelease_controller.go
Labels: bug

#146 Helm chart divergences fixes
  api/v2beta1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  docs/spec/v2beta1/helmreleases.md
Labels: bug

#148 Refactor to adopt k8s standardized Condition type
  api/go.mod
  api/go.sum
  api/v2beta1/helmrelease_types.go
  api/v2beta1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  config/default/kustomization.yaml
  controllers/helmrelease_controller.go
  controllers/helmrelease_controller_test.go
  docs/api/helmrelease.md
  go.mod
  go.sum
  hack/api-docs/config.json
Labels: enhancement

#156 Requeue after interval on source not found errors
  controllers/helmrelease_controller.go
Labels: area/helm

#155 Add the impersonation feature to API spec
  docs/spec/v2beta1/helmreleases.md
Labels: area/docs

#157 Implement service account impersonation
  .github/workflows/e2e.yaml
  api/v2beta1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  config/testdata/impersonation/test.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
Labels: area/helm, enhancement

#159 Cleanup end-to-end test objects after each run
  .github/workflows/e2e.yaml
  config/testdata/dependencies/helmrelease-backend.yaml
  config/testdata/dependencies/helmrelease-frontend.yaml
  config/testdata/dependencies/helmrepository.yaml
  config/testdata/sources/gitrepository.yaml
  config/testdata/sources/helmrepository.yaml
  config/testdata/valuesfrom/helmrelease.yaml
  config/testdata/valuesfrom/helmrepository.yaml
Labels: area/build

#163 Add readiness/liveness probes
  Makefile
  api/go.mod
  api/go.sum
  config/manager/deployment.yaml
  go.mod
  go.sum
  main.go
Labels: enhancement

#169 Ignore missing release on HR delete
  controllers/helmrelease_controller.go
Labels: bug
