Repository fluxcd/helm-controller, pull requests merged in 2020-10, with the labels that each got.

#102 Configure release namespace in runner constructor
  .github/workflows/e2e.yaml
  config/testdata/targetnamespace/helmrelease.yaml
  controllers/helmrelease_controller.go
  internal/runner/runner.go
Labels: bug

#106 Set default branch to main
  .github/workflows/e2e.yaml
  .github/workflows/fossa.yml
  .github/workflows/release.yml
  README.md
  docs/internal/release.md
  docs/spec/v2alpha1/helmreleases.md
  docs/spec/v2beta1/helmreleases.md
Labels: area/build

#109 Implement Prometheus instrumentation
  api/go.mod
  api/go.sum
  controllers/helmrelease_controller.go
  go.mod
  go.sum
  main.go
Labels: enhancement

#110 Add namespace to API docs examples
  docs/spec/v2beta1/helmreleases.md
Labels: area/docs

#114 Declare and assign result Values before composing
  controllers/helmrelease_controller.go
  controllers/helmrelease_controller_test.go
  go.mod
Labels: bug

#115 Change chart reconciliation and readiness logic
  controllers/helmrelease_controller.go
Labels: bug

#122 Fixing typo (issue #118)
  docs/spec/v2alpha1/helmreleases.md
  docs/spec/v2beta1/helmreleases.md
Labels: area/docs

#119 Support cross-cluster Helm releases
  api/v2beta1/helmrelease_types.go
  api/v2beta1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
  docs/spec/v2beta1/helmreleases.md
  internal/kube/client.go
  internal/runner/runner.go
Labels: area/helm, enhancement

#131 Move dedicated watcher to in-controller watcher
  config/rbac/role.yaml
  controllers/helmchart_watcher.go
  controllers/helmrelease_controller.go
  main.go
Labels: enhancement

#134 Update pkg/runtime API dependency to v0.1.2
  api/go.mod
  api/go.sum
Labels: area/build

#128 Upgrade Helm to v3.4.0
  go.mod
  go.sum
Labels: area/helm, enhancement
