Repository fluxcd/helm-controller, pull requests merged in 2021-06, with the labels that each got.

#271 Add support for Helm `--wait-for-jobs` flag
  api/v2beta1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/helmrelease.md
  docs/spec/v2beta1/helmreleases.md
  internal/runner/runner.go
Labels: area/helm, enhancement

#274 Add nightly builds workflow and allow RC releases
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yml
Labels: area/build

#277 Update Helm and source-controller
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build, area/helm

#287 e2e: Update Kubernetes to v1.21
  .github/workflows/e2e.yaml
Labels: area/build
