Repository fluxcd/helm-controller, pull requests merged in 2021-03, with the labels that each got.

#229 fix: log messages contain '%s'
  controllers/helmrelease_controller.go
Labels: area/UX, bug

#232 Update dependencies
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#234 Record suspend metrics
  controllers/helmrelease_controller.go
Labels: area/UX, enhancement

#236 Record suspension metrics
  api/go.mod
  api/go.sum
  controllers/helmrelease_controller.go
  go.mod
  go.sum
Labels: enhancement

#238 Label release resources with HelmRelease origin
  internal/runner/post_renderer_origin_labels.go
  internal/runner/post_renderer_origin_labels_test.go
  internal/runner/runner.go
Labels: area/UX, enhancement

#239 Set leader election deadline to 30s
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  main.go
Labels: enhancement

#219 Capture and expose debug (log) information on release failure
  controllers/helmrelease_controller.go
  internal/runner/log_buffer.go
  internal/runner/log_buffer_test.go
  internal/runner/runner.go
Labels: area/UX, area/helm, enhancement

#240 Update source-controller API to v0.10.0
  go.mod
  go.sum
Labels: area/build
