Repository fluxcd/helm-controller, pull requests merged in 2021-01, with the labels that each got.

#187 docs Update helmreleases.md dependsOn
  docs/spec/v2beta1/helmreleases.md
Labels: area/docs

#183 Upgrade controller-runtime to v0.7.0
  api/go.mod
  api/go.sum
  config/manager/deployment.yaml
  config/rbac/leader_election_role.yaml
  controllers/helmrelease_controller.go
  controllers/helmrelease_controller_chart.go
  controllers/helmrelease_controller_chart_test.go
  controllers/helmrelease_controller_test.go
  controllers/source_predicate.go
  controllers/suite_test.go
  go.mod
  go.sum
  internal/util/util.go
  main.go
Labels: area/build

#188 Publish as single multi-arch Docker image
  .github/workflows/release.yml
Labels: area/build

#189 Upgrade source-controller to v0.6.0
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#192 Upgrade runtime package to v0.6.2
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  controllers/helmrelease_controller.go
  go.mod
  go.sum
Labels: area/build

#194 Update K8s, Helm, source API and ctrl-runtime deps
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#195 Update `source-controller` manifests to `v0.6.2`
  config/default/kustomization.yaml
Labels: area/build

#197 Update fluxcd/pkg/runtime to v0.8.0
  api/go.mod
  api/go.sum
  api/v2beta1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/helmrelease.md
  go.mod
  go.sum
  main.go
Labels: area/build

#198 Make Helm storage namespace configurable
  api/v2beta1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
Labels: area/UX, area/helm, enhancement

#201 Document StorageNamespace field
  docs/spec/v2beta1/helmreleases.md
Labels: area/docs
