Repository fluxcd/helm-controller, pull requests merged in 2021-04, with the labels that each got.

#243 Add CodeQL and Snyk scan
  .github/workflows/fossa.yml
  .github/workflows/scan.yaml
Labels: area/build

#251 Update fluxcd/pkg/runtime to v0.10.2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#252 Add `ValuesFiles` to HelmChart spec
  api/v2beta1/helmrelease_types.go
  api/v2beta1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller_chart.go
  controllers/helmrelease_controller_chart_test.go
  docs/api/helmrelease.md
  go.mod
  go.sum
Labels: area/helm

#250 Initial support for HelmRelease for upgrading CRDs
  .github/workflows/e2e.yaml
  api/v2beta1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  config/testdata/charts/crds/bootstrap/.helmignore
  config/testdata/charts/crds/bootstrap/Chart.yaml
  config/testdata/charts/crds/bootstrap/templates/git-repository.yaml
  config/testdata/charts/crds/bootstrap/values.yaml
  config/testdata/charts/crds/v1/.helmignore
  config/testdata/charts/crds/v1/Chart.yaml
  config/testdata/charts/crds/v1/crds/a.yaml
  config/testdata/charts/crds/v1/crds/b.yaml
  config/testdata/charts/crds/v1/crds/d.yaml
  config/testdata/charts/crds/v1/templates/dummy.yaml
  config/testdata/charts/crds/v1/values.yaml
  config/testdata/charts/crds/v2/.helmignore
  config/testdata/charts/crds/v2/Chart.yaml
  config/testdata/charts/crds/v2/crds/a.yaml
  config/testdata/charts/crds/v2/crds/b.yaml
  config/testdata/charts/crds/v2/crds/c.yaml
  config/testdata/charts/crds/v2/templates/dummy.yaml
  config/testdata/charts/crds/v2/values.yaml
  config/testdata/crds-upgrade/create-replace/helmrelease.yaml
  config/testdata/crds-upgrade/create/helmrelease.yaml
  config/testdata/crds-upgrade/init/helmrelease.yaml
  docs/api/helmrelease.md
  docs/spec/v2beta1/helmreleases.md
  internal/runner/runner.go
Labels: enhancement

#253 Update dependencies
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  docs/spec/v2beta1/helmreleases.md
  go.mod
  go.sum
Labels: area/build

#246 docs: minor `createNamespace` placement fix
  docs/spec/v2beta1/helmreleases.md
Labels: area/docs
