Repository fluxcd/helm-controller, pull requests merged in 2021-02, with the labels that each got.

#202 Support for Kustomize based PostRenderer
  .github/workflows/e2e.yaml
  api/go.sum
  api/v2beta1/helmrelease_types.go
  api/v2beta1/kustomization_types.go
  api/v2beta1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  config/testdata/post-renderer-kustomize/helmrelease.yaml
  controllers/helmrelease_types_test.go
  docs/api/helmrelease.md
  docs/spec/v2beta1/helmreleases.md
  go.mod
  go.sum
  internal/runner/post_renderer.go
  internal/runner/post_renderer_kustomize.go
  internal/runner/runner.go
Labels: area/helm, enhancement

#205 Depend on the Kustomize API from `fluxcd/pkg`
  api/go.mod
  api/go.sum
  api/v2beta1/helmrelease_types.go
  api/v2beta1/kustomization_types.go
  api/v2beta1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_types_test.go
  docs/api/helmrelease.md
  docs/spec/v2beta1/helmreleases.md
  go.mod
  go.sum
  hack/api-docs/config.json
  hack/boilerplate.go.txt
  internal/runner/post_renderer.go
  internal/runner/post_renderer_kustomize.go
  internal/runner/runner.go
Labels: area/build

#207 Update dependencies
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#209 Enable pprof endpoints on metrics server
  go.mod
  go.sum
  main.go
Labels: area/build

#210 Update Alpine to v3.13
  Dockerfile
Labels: area/build

#215 List Kustomize post renderer in README
  README.md
Labels: area/docs

#216 Allow the controller to be run locally
  CONTRIBUTING.md
  controllers/helmrelease_controller_chart.go
Labels: area/UX, area/docs

#217 add a release deployment event when reconciling a release
  controllers/helmrelease_controller.go
Labels: area/UX

#220 Use `MergeMaps` from pkg/runtime v0.8.2
  controllers/helmrelease_controller.go
  go.mod
  go.sum
  internal/util/util.go
  internal/util/util_test.go
Labels: area/build

#223 Refactor release workflow
  .github/workflows/release.yml
Labels: area/build

#225 Update dependencies
  Makefile
  api/go.mod
  api/go.sum
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  go.mod
  go.sum
Labels: area/build

#226 Use source-controller manifest from GitHub release
  config/default/kustomization.yaml
Labels: area/build

#228 Retry with exponential backoff when fetching artifacts
  controllers/helmrelease_controller.go
  controllers/helmrelease_controller_chart.go
  go.mod
  main.go
Labels: enhancement
