Repository fluxcd/helm-controller, pull requests merged in 2022-12, with the labels that each got.

#570 Allow overriding ctrl manager graceful shutdown timeout
  main.go
Labels: enhancement

#578 fuzz: Use build script from upstream and fix fuzzers
  go.mod
  go.sum
  tests/fuzz/Dockerfile.builder
  tests/fuzz/oss_fuzz_build.sh
  tests/fuzz/oss_fuzz_run.sh
Labels: area/build

#577 helm: Update SDK to v3.10.3
  go.mod
  go.sum
Labels: area/helm, area/build

#580 Minor typo in doc
  docs/spec/v2alpha1/helmreleases.md
  docs/spec/v2beta1/helmreleases.md
Labels: area/docs

#581 Update source-controller and dependencies
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build
