Repository fluxcd/helm-controller, pull requests merged in 2022-03, with the labels that each got.

#431 Update links to kubectl documentation
  docs/spec/v2beta1/helmreleases.md
Labels: area/docs

#434 Update Helm to v3.8.1
  go.mod
  go.sum
Labels: area/build

#432 Support targeted Patches in the PostRenderer specification
  api/v2beta1/helmrelease_types.go
  api/v2beta1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/helmrelease.md
  docs/spec/v2beta1/helmreleases.md
  internal/runner/post_renderer_kustomize.go
  internal/runner/post_renderer_kustomize_test.go
Labels: enhancement, area/kustomize

#436 Update {containerd: v1.5.10, kustomize: v4.5.2} and tidy go.mod
  go.mod
  go.sum
  tests/fuzz/go.mod
Labels: area/build, area/kustomize

#440 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#441 Run tidy before Go test
  Makefile
  api/go.sum
  go.sum
Labels: area/build

#445 Update source-controller API to v0.22.1
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#449 Update Kustomize to v4.5.3
  go.mod
  go.sum
Labels: area/build, area/kustomize

#452 Align version of dependencies when Fuzzing
  tests/fuzz/oss_fuzz_build.sh
Labels: area/build
