Repository fluxcd/helm-controller, pull requests merged in 2022-04, with the labels that each got.

#456 update docs links to toolkit.fluxcd.io
  README.md
Labels: area/docs

#466 Update helm.sh/helm/v3 to v3.8.2
  go.mod
  go.sum
Labels: area/helm, area/build

#467 Update dependencies
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#465 Add flags for exponential back-off retry
  controllers/helmrelease_controller.go
  main.go
Labels: enhancement

#470 Update source-controller to v0.24.1
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#461 Support defining a KubeConfig Secret data key
  api/go.mod
  api/go.sum
  api/v2beta1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  docs/api/helmrelease.md
  go.mod
  go.sum
Labels: enhancement

#472 kubeconfig: err on missing declared SecretRef.Key
  controllers/helmrelease_controller.go
Labels: enhancement
