Repository fluxcd/helm-controller, pull requests merged in 2022-01, with the labels that each got.

#380 Update Helm to v3.7.2
  go.mod
  go.sum
Labels: area/build

#348 Update Go to v1.17
  .github/workflows/e2e.yaml
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  api/v2beta1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  controllers/helmrelease_controller.go
  controllers/helmrelease_controller_chart.go
  controllers/helmrelease_controller_chart_test.go
  controllers/helmrelease_controller_test.go
  go.mod
  go.sum
  internal/runner/log_buffer_test.go
Labels: area/build

#392 Use go-install-tool for gen-crd-api-reference-docs
  Makefile
Labels: area/build

#397 Update development documentation
  DEVELOPMENT.md
Labels: area/docs

#385 security: Drop capabilities, set userid and enable seccomp
  Dockerfile
  config/manager/deployment.yaml
  go.mod
Labels: area/build

#401 Publish SBOM and sign release artifacts
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yml
  .github/workflows/scan.yaml
  .goreleaser.yaml
Labels: enhancement, area/build

#407 Update helm to 3.7.2
  go.mod
  go.sum
Labels: area/build

#409 Update Helm to patched 3.8.0
  .github/workflows/e2e.yaml
  Makefile
  go.mod
  go.sum
Labels: area/helm, area/build

#408 Allow disabling cross-namespace references
  controllers/helmrelease_controller.go
  controllers/helmrelease_controller_chart.go
  controllers/helmrelease_controller_chart_test.go
  docs/spec/v2beta1/helmreleases.md
  go.mod
  go.sum
  main.go
Labels: enhancement

#406 Allow setting a default service account for impersonation
  controllers/helmrelease_controller.go
  docs/spec/v2beta1/helmreleases.md
  go.mod
  go.sum
  internal/kube/client.go
  main.go
Labels: enhancement
