Repository fluxcd/helm-controller, pull requests merged in 2023-05, with the labels that each got.

#685 Update Alpine to 3.18
  Dockerfile
Labels: area/build

#684 Stable sort release values by key
  api/v2beta1/helmrelease_types.go
  go.mod
  internal/controllers/helmrelease_controller.go
  internal/util/util.go
  internal/util/util_test.go
Labels: enhancement

#687 Update dependencies
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies

#690 Update Kubernetes, controller-runtime and Helm
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  internal/controllers/helmrelease_controller.go
  internal/runner/post_renderer_kustomize.go
  main.go
Labels: area/helm, dependencies

#691 Remove the tini supervisor, and other nits
  Dockerfile
  Makefile
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  config/rbac/role.yaml
  internal/controller/helmrelease_controller.go
  internal/controller/helmrelease_controller_chart.go
  internal/controller/helmrelease_controller_chart_test.go
  internal/controller/helmrelease_controller_fuzz_test.go
  internal/controller/helmrelease_controller_test.go
  internal/controller/source_predicate.go
  internal/controller/suite_test.go
  main.go
Labels: area/build

#692 Use last attempted values checksum as event metadata token
  internal/controller/helmrelease_controller.go
Labels: enhancement

#693 Update source-controller to v1.0.0-rc.4
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies

#695 Include revision and token in event metadata
  internal/controller/helmrelease_controller.go
Labels: bug
