Repository fluxcd/helm-controller, pull requests merged in 2023-12, with the labels that each got.

#823 Introduce `forceAt` and `resetAt` annotations
  api/v2beta2/annotations.go
  api/v2beta2/annotations_test.go
  api/v2beta2/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/v2beta2/helm.md
  internal/action/reset.go
  internal/action/reset_test.go
  internal/controller/helmrelease_controller.go
  internal/reconcile/atomic_release.go
  internal/reconcile/atomic_release_test.go
Labels: enhancement, area/api

#832 api: deprecate stragic merge and JSON 6902 patches
  api/v2beta2/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/v2beta2/helm.md
Labels: area/api

#836 ci: increase timeout delete-ns tests
  .github/workflows/e2e.yaml
Labels: area/ci

#838 build: update Alpine to 3.19
  Dockerfile
Labels: area/ci, dependencies

#839 Update Kustomize to v5.3.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/kustomize, dependencies

#828 docs/spec: document `v2beta2` API
  README.md
  docs/spec/README.md
  docs/spec/v2beta2/README.md
  docs/spec/v2beta2/helmreleases.md
Labels: area/docs

#843 docs/spec: address typo
  docs/spec/v2beta2/helmreleases.md
Labels: area/docs

#845 loader: log HTTP errors to provide faster feedback
  internal/controller/helmrelease_controller.go
  internal/controller/helmrelease_controller_test.go
  internal/loader/client.go
Labels: area/ux

#846 Update runtime to v0.43.3
  go.mod
  go.sum
Labels: dependencies

#849 Update Helm to v3.13.3
  go.mod
  go.sum
Labels: dependencies

#848 Early stall condition detection after remediation
  internal/reconcile/atomic_release.go
  internal/reconcile/atomic_release_test.go
Labels: area/ux

#851 api: ensure backwards compatibility v2beta1
  api/v2beta1/helmrelease_types.go
  api/v2beta1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
Labels: area/api

#858 Properly configure namespace selector
  main.go
Labels: bug
