Repository fluxcd/helm-controller, pull requests merged in 2023-06, with the labels that each got.

#696 Bump source-controller to v1.0.0-rc.5
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies

#705 Add SLSA3 generators to release workflow
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: area/build

#707 Enable Dependabot for GH Actions
  .github/dependabot.yaml
  .goreleaser.yaml
Labels: area/build

#714 scan: disable Snyk
  .github/workflows/scan.yaml
Labels: area/build

#715 Align `go.mod` version with Kubernetes (Go 1.20)
  DEVELOPMENT.md
  api/go.mod
  go.mod
  tests/fuzz/Dockerfile.builder
Labels: area/build

#718 Add backport GitHub Action workflow
  .github/dependabot.yaml
  .github/labels.yaml
  .github/workflows/backport.yaml
  .github/workflows/sync-labels.yaml
Labels: enhancement, area/build

#698 Set deletion propagation for helm uninstall
  api/v2beta1/helmrelease_types.go
  api/v2beta1/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/helmrelease.md
  docs/spec/v2beta1/helmreleases.md
  internal/runner/runner.go
Labels: enhancement, area/helm, area/api
