Repository fluxcd/helm-controller, pull requests merged in 2023-08, with the labels that each got.

#749 ci: enable security-and-quality CodeQL query
  .github/workflows/scan.yaml
Labels: area/ci

#748 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#751 controller: jitter requeue interval
  api/v2beta1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/v2beta1/helm.md
  docs/spec/v2beta1/helmreleases.md
  internal/controller/helmrelease_controller.go
  main.go
Labels: enhancement

#754 Update Helm to v3.12.3
  go.mod
  go.sum
Labels: dependencies

#753 Delete stale metrics on object delete
  go.mod
  go.sum
  internal/controller/helmrelease_controller.go
  main.go
Labels: enhancement

#758 Update Source API to v1.1.0
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies, area/testing
