Repository fluxcd/helm-controller, pull requests merged in 2023-09, with the labels that each got.

#768 Check source for nil artifact before loading chart
  internal/controller/helmrelease_controller_chart.go
Labels: bug

#767 runner: address regression in captured Helm logs
  internal/controller/helmrelease_controller.go
  internal/runner/runner.go
Labels: bug

#774 controller: use `DefaultServiceAccount` in differ
  internal/controller/helmrelease_controller.go
Labels: bug, area/drift

#775 Update source-controller to v1.1.1
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies

#777 fix: Typo
  docs/spec/v2beta1/helmreleases.md
Labels: area/docs
