Repository fluxcd/helm-controller, pull requests merged in 2023-02, with the labels that each got.

#606 Support RFC-0005 revision format
  config/default/kustomization.yaml
  controllers/helmrelease_controller.go
  controllers/source_predicate.go
  go.mod
  go.sum
Labels: enhancement

#610 Update dependencies
  Makefile
  api/go.mod
  api/go.sum
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  go.mod
  go.sum
Labels: area/build

#612 Update source-controller to v0.35.1
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#614 ci: Fix Snyk code scanning
  .github/workflows/scan.yaml
Labels: area/build

#620 helm: propagate context to install and upgrade
  controllers/helmrelease_controller.go
  internal/runner/runner.go
Labels: area/helm
