Repository fluxcd/helm-controller, pull requests merged in 2023-11, with the labels that each got.

#812 Update github.com/docker/docker to 24.0.7
  go.mod
  go.sum
Labels: dependencies, go

#817 Update to Kubernetes 1.28.x, Helm v3.13.2 and Kustomize v5.2.1
  api/go.mod
  api/go.sum
  api/v2beta2/helmrelease_types.go
  go.mod
  go.sum
  internal/controller/helmrelease_controller.go
  internal/diff/differ_test.go
  internal/reconcile/atomic_release.go
  internal/release/digest_test.go
  internal/release/observation.go
  internal/release/observation_test.go
  internal/yaml/encode.go
  internal/yaml/sort.go
  internal/yaml/sort_test.go
  main.go
Labels: dependencies

#815 Allow configuration of drift detection on `HelmRelease`
  api/v2beta2/helmrelease_types.go
  api/v2beta2/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/v2beta2/helm.md
  go.mod
  go.sum
  internal/action/diff.go
  internal/action/diff_test.go
  internal/diff/differ.go
  internal/diff/differ_test.go
  internal/diff/summarize.go
  internal/diff/summarize_test.go
  internal/reconcile/atomic_release.go
  internal/reconcile/atomic_release_test.go
  internal/reconcile/state.go
  internal/reconcile/state_test.go
Labels: enhancement, area/drift

#819 Remove obsolete code and tidy things
  internal/action/diff.go
  internal/action/verify.go
  internal/action/verify_test.go
  internal/controller/helmrelease_controller.go
  internal/controller/helmrelease_controller_test.go
  internal/features/features.go
  internal/reconcile/atomic_release.go
  internal/reconcile/atomic_release_test.go
  internal/reconcile/state.go
  internal/runner/log_buffer.go
  internal/runner/log_buffer_test.go
  internal/runner/runner.go
  internal/util/object.go
  main.go
Labels: hold

#818 Allow configuration of snapshot digest algorithm
  internal/digest/digest.go
  internal/digest/digest_test.go
  main.go
Labels: enhancement

#821 Add deprecation warning to v2beta1 API
  api/v2beta1/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
Labels: area/api

#822 Correct cluster drift using patches
  go.mod
  go.sum
  internal/action/diff.go
  internal/action/diff_test.go
  internal/diff/summarize.go
  internal/diff/summarize_test.go
  internal/reconcile/atomic_release.go
  internal/reconcile/atomic_release_test.go
  internal/reconcile/correct_cluster_drift.go
  internal/reconcile/correct_cluster_drift_test.go
  internal/reconcile/reconcile.go
  internal/reconcile/release_test.go
  internal/reconcile/state_test.go
Labels: enhancement, area/drift
