Repository fluxcd/helm-controller, pull requests merged in 2023-07, with the labels that each got.

#725 ci: update kind to v0.19.0
  .github/workflows/e2e.yaml
Labels: area/ci, dependencies

#726 Update Go dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#727 ci: various workflow changes
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yml
  .github/workflows/scan.yaml
Labels: area/ci

#729 Update source-controller to v1.0.0
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies

#730 ci: update Kubernetes to v1.27.3
  .github/workflows/e2e.yaml
Labels: area/ci, dependencies

#731 ci: use bot token for backport
  .github/workflows/backport.yaml
Labels: area/ci

#732 ci: group Dependabot GitHub Action updates
  .github/dependabot.yaml
Labels: area/ci, dependencies

#734 Fix GHA backport.yaml workflow job perms
  .github/workflows/backport.yaml
  .github/workflows/release.yml
Labels: area/ci
