Repository fluxcd/helm-controller, pull requests merged in 2024-04, with the labels that each got.

#879 Update controller to Helm v3.14.3 and Kubernetes v1.29.0
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yaml
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  internal/kube/client.go
  internal/kube/client_test.go
  tests/fuzz/Dockerfile.builder
Labels: dependencies

#930 Add `notation` verification provider to API
  api/v2beta2/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
Labels: area/api

#932 Update dependencies to Kustomize v5.4.0
  go.mod
  go.sum
Labels: dependencies

#935 Fix patching on drift detection
  internal/reconcile/atomic_release.go
Labels: bug

#905 Add support for `OCIRepository` as chartRef
  .github/workflows/e2e.yaml
  api/v2beta2/helmrelease_types.go
  api/v2beta2/reference_types.go
  api/v2beta2/snapshot_types.go
  api/v2beta2/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  config/rbac/role.yaml
  config/testdata/install-from-ocirepo-source/test.yaml
  config/testdata/upgrade-from-ocirepo-source/install.yaml
  config/testdata/upgrade-from-ocirepo-source/upgrade.yaml
  docs/api/v2beta2/helm.md
  docs/spec/v2beta2/helmreleases.md
  go.mod
  go.sum
  internal/action/reset.go
  internal/action/verify.go
  internal/controller/helmrelease_controller.go
  internal/controller/helmrelease_controller_test.go
  internal/reconcile/correct_cluster_drift.go
  internal/reconcile/helmchart_template.go
  internal/reconcile/helmchart_template_test.go
  internal/reconcile/install.go
  internal/reconcile/install_test.go
  internal/reconcile/release.go
  internal/reconcile/release_test.go
  internal/reconcile/rollback_remediation.go
  internal/reconcile/rollback_remediation_test.go
  internal/reconcile/test.go
  internal/reconcile/test_test.go
  internal/reconcile/uninstall.go
  internal/reconcile/uninstall_remediation.go
  internal/reconcile/uninstall_test.go
  internal/reconcile/unlock.go
  internal/reconcile/unlock_test.go
  internal/reconcile/upgrade.go
  internal/reconcile/upgrade_test.go
  internal/release/digest_test.go
  internal/release/observation.go
Labels: enhancement

#945 Add support for `HelmChart` as chartRef
  .github/workflows/e2e.yaml
  api/v2beta2/reference_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  config/testdata/install-from-hc-source/test.yaml
  docs/spec/v2beta2/helmreleases.md
  internal/controller/helmrelease_controller_test.go
Labels: enhancement

#944 Update dependencies to Kubernetes 1.30
  Makefile
  api/go.mod
  api/go.sum
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  go.mod
  go.sum
Labels: dependencies

#885 Update Ready condition during drift correction
  internal/reconcile/correct_cluster_drift.go
  internal/reconcile/correct_cluster_drift_test.go
Labels: bug
