Repository fluxcd/helm-controller, pull requests merged in 2024-09, with the labels that each got.

#1060 Allow overwriting inline values with targetPath
  docs/spec/v2/helmreleases.md
  docs/spec/v2beta2/helmreleases.md
  internal/chartutil/values.go
  internal/chartutil/values_test.go
Labels: area/helm

#1062 Update Helm to v3.16.1 and enable the adoption of existing resources
  go.mod
  go.sum
  internal/action/install.go
  internal/action/upgrade.go
Labels: area/helm

#1068 Add `disableSchemaValidation` to Helm install/upgrade actions
  api/v2/helmrelease_types.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/v2/helm.md
  docs/spec/v2/helmreleases.md
  internal/action/install.go
  internal/action/upgrade.go
Labels: area/api

#1071 Update flux deps and k8s deps to 1.31.1
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies

#1073 Update source-controller to v1.4.1
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies
