Repository fluxcd/helm-controller, pull requests merged in 2025-07, with the labels that each got.

#1258 Introduce label selector for watching ConfigMaps and Secrets
  api/go.mod
  api/go.sum
  docs/spec/v2/helmreleases.md
  go.mod
  go.sum
  internal/controller/helmrelease_controller.go
  main.go
Labels: enhancement

#1262 [RFC-0010] Support all Azure clouds for remote clusters at the controller level
  go.mod
  go.sum
Labels: enhancement, area/security

#1266 Fix watch index conflict between HelmChart and OCIRepository kinds
  internal/controller/helmrelease_controller.go
Labels: bug

#1271 Extend the readiness evaluation of dependencies with CEL expressions
  api/v2/helmrelease_types.go
  api/v2/reference_types.go
  api/v2/zz_generated.deepcopy.go
  config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
  docs/api/v2/helm.md
  docs/spec/v2/helmreleases.md
  go.mod
  go.sum
  internal/controller/helmrelease_controller.go
  internal/controller/helmrelease_controller_test.go
  internal/controller/helmrelease_indexers.go
  internal/controller/helmrelease_manager.go
  internal/features/features.go
  main.go
Labels: enhancement, area/ux, area/api

#1276 Fix requeue interval for SourceNotReady
  internal/controller/helmrelease_controller.go
  internal/controller/helmrelease_controller_test.go
Labels: bug, area/drift
